config/routes.rb
Rails.application.routes.draw do

	root "users#home"

	get "signin" => "sessions#new"
	resource :session, :except => [:new]

	get "home" => "users#home"
  get "players" => "users#index"
  get "signup" => "users#new"
  get "news" => "blogs#news"
  resources :users, :except => [:home, :index, :new] do
  	resources :blogs, :except => [:news, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	validates :content, presence: true

  belongs_to :user

  def self.newest
  	Blog.all.order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password

	validates :name, presence: true
  validates :username, presence: true,
  										 length: { minimum: 6 },
  										 format: /\A\w+\z/,
  										 uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                    format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
                    uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 5, allow_blank: true }
	validates :number, inclusion: { in: 0..100 }
  has_many :blogs, dependent: :destroy

	def gravatar_id
		Digest::MD5::hexdigest(email.downcase)
	end

  def self.authenticate(email_or_username, password)
    user = User.find_by(email: email_or_username) || User.find_by(username: email_or_username)
    user && user.authenticate(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_signin
  	unless current_user
  		session[:intended_url] = request.url
      flash[:error] = "This page requires signin"
  		redirect_to signin_path
  	end
  	#unless there is somebody signed in redirect them to the signin page
  end

  def require_admin
  	unless current_user_admin?
      flash[:error] = "Unauthorized Access"
  		redirect_to root_path
  	end
  end

  helper_method :require_admin

  def current_user_admin?
  	current_user && current_user.admin?
  end

  helper_method :current_user_admin?

	def current_user?(user)
		user == current_user
		#is this user the current user?
	end

	helper_method :current_user?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def any_user?
    User.any?
  end

  helper_method :any_user?
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :require_signin, only: [:news]

	def news
		set_current_user
		@blog = @user.blogs.new
		@blogs= Blog.order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
	end

	def index
		@user = User.find(params[:user_id])
		@blogs = @user.blogs
	end

	def show
	end

	def new
		set_current_user
		@blog = @user.blogs.new
	end

	def create
		set_current_user
		@blog = @user.blogs.new(blog_params)
		if @blog.save
			redirect_to news_path
			flash[:success] = "Posted"
		else
			render :new
		end
	end

	def edit
	end

	def destroy
		@blog = Blog.find(params[:id])
		@user = User.find(@blog.user_id)
		@blog.destroy
		redirect_to user_blogs_path(@user), alert: "Deleted"
	end

private

	def blog_params
		params.require(:blog).permit(:content, :title)
	end

	def set_current_user
		@user = current_user
	end

end

# There is no difference between using params[:user_id] vs params[:id]
# But since I'm fetching a User instance in the Blog controller
# It is better to use :user_id

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@disable_nav = true
		if current_user
			redirect_to current_user
		end
	end

	def create
		if @user = User.authenticate(params[:email_or_username], params[:password])
			session[:user_id] = @user.id
			redirect_to(session[:intended_url] || @user)
			flash[:success] = "Signed in as #{@user.name}"
			session[:intended_url] = nil
		else
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, alert: "Signed out"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_signin, only: [:show]
	before_action :require_correct_user, only: [:edit, :update, :destroy]

	def home
		@disable_nav = true
	end

	def index
		@users = User.order(number: :asc)
	end

	def show
		set_user
	end

	def new
		@disable_nav = true
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user
			flash[:success] = "Welcome '#{@user.name}'!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user
			flash[:success] = "'#{@user.name}' was updated"
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if current_user?(@user)
		redirect_to players_path, alert: "'#{@user.name}' was deleted"
	end

end

private
	
	def user_params
		params.require(:user).permit(:name, :email, :username, :number, :password, :password_confirmation, :intro)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_correct_user
		set_user
		unless current_user?(@user) || current_user_admin?
			#unless the dude that's signed in is the dude that's being deleted
			#or the dude that's signed in is an admin
			redirect_to root_path
      flash[:error] = "Unauthorized Access"
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_id(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    default_url = "http://imgur.com/GxCWoX7"
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=500&r=g"
	end
	
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-custom #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/blogs/_form.html.erb
<%= form_for [@user, @blog] do |f| %>

	<%= render "shared/errors" %>

	<h4>What you would like to say?</h4>

	<div class="form-group">
	  <%= f.label :title, "Title:", class: "sr-only" %>
	  <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="form-group">
	  <%= f.label :content, "Content:", class: "sr-only" %>
	  <%= f.text_area :content, class: "form-control", rows: 7 %>
  </div>

	<%= submit_tag "Post", class: "btn btn-primary" %>
	<% unless current_page?(news_url) %>
		<%= link_to "Cancel", news_path, class: "btn btn-primary" %>
	<% end %>
<% end %>

app/views/blogs/index.html.erb
<body>
	<div class="container">
	    <div class="row">
	        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	            <% @blogs.each do |b| %>
	            <% @user = b.user %>
	            <div class="post-preview">
									<h2 class="post-title">
										<%= b.title %>
									</h2>	                
									<h4 class="post-subtitle">
                    <%= b.content %>
                  </h4>
	                <p class="post-meta">Posted by <%= link_to(@user.name, user_path(@user)) %> <%= time_ago_in_words(b.created_at) %> ago</p>
	            </div>
	            <hr>
	            <% end %>
	        </div>
	    </div>
	</div>
</body>
<%= render "layouts/footer" %>

app/views/blogs/new.html.erb
<body>
	<div class="container form-padding">
		<div class="row">
		  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
		  	<div class="well text-center">
					<%= render "form" %>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/blogs/news.html.erb
<body>
	<div class="container">
	    <div class="row">
	        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	            <% @blogs.each do |b| %>
	            <% @user = b.user %>
	            <div class="post-preview">
									<h2 class="post-title">
										<%= b.title %>
									</h2>	                
									<h4 class="post-subtitle">
                    <%= b.content %>
                  </h4>
	                <p class="post-meta">Posted by <%= link_to(@user.name, user_path(@user)) %> <%= time_ago_in_words(b.created_at) %> ago</p>
	            </div>
	            <hr>
	            <% end %>
	            <div class="pagniation-wrapper">
		            <%= will_paginate @blogs,
		             :renderer => BootstrapPagination::Rails,
		            previous_label: h("newer"), next_label: h("older") %>
	            </div>
	            <div class="well text-center">
		            <%= render "form" %>
	            </div>
	        </div>
	    </div>
	</div>
</body>
  
<%= render '/layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h4><strong>Rush N Catch</strong>
                </h4>
                <p>South Korea</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">rushncatch@gmail.com</a>
                    </li>
                </ul>
                <br>
                <ul class="list-inline">
                    <li>
                        <a href="http://www.facebook.com/rushncatch"><i class="fa fa-facebook fa-fw fa-4x"></i></a>
                    </li>
                </ul>
                <hr>
                <p class="text-muted">Copyright &copy; Il Soo Yang 2016</p>
            </div>
        </div>
    </div>
    <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
</footer>

app/views/layouts/_navbar_top.html.erb
<div class="navbar navbar-custom">
    <div class="container-fluid"> 
        
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#home-news-users" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo2.png"), home_path, class: "navbar-brand" %>
        </div>
        
        <div class="collapse navbar-collapse" id="home-news-users">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("News", news_path) %>
                </li>
                <li>
                    <%= link_to("Players", players_path) %>
                </li>
                <% if any_user? && current_user %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to("Write", new_user_blog_path(current_user)) %>
                            </li>
                            <li>
                                <%= link_to("Account Settings", 
                                    edit_user_path(current_user)) %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <%= link_to("Sign Out", 
                                    session_path, method: :delete) %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to("Sign In", signin_path) %></li>
                <% end %>
            </ul>        
        </div>
    </div>
    <%= flash_messages %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rush N Catch</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

    <!-- jQuery -->
    <script href="assets/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script href="assets/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= render "layouts/navbar_top" unless @disable_nav %>
    <%= yield %>
  </body>

    <!-- Custom Theme JavaScript -->
    <script type="text/javascript">

    // Carousel
    $(document).ready(function() {
        $('.carousel').carousel({
          interval: 2000
        })
    });

    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    </script>
    
</html>

app/views/players/home.html.erb
<body>

    <div class="container" id="top">
        <%= image_tag("logo2.png", class: "header") %>
    </div>

    <!-- <header id="top" class="header"></header> -->

    <div class="container">
        <hr>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 text-center">
                <%= link_to news_path do %>
                    <span class="fa fa-newspaper-o" 
                    style="font-size: 3em; color: #000000"></span>
                <% end %>
                <h3>RnC News</h3>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 text-center">
                <%= link_to players_path do %>
                    <span class="glyphicon glyphicon-user" 
                    style="font-size: 3em; color: #000000"></span>
                <% end %>
                <h3>Meet the players</h3>
            </div>
        </div>
        <hr>
    </div>

</body>

<%= render '/layouts/footer' %>

app/views/players/index.html.erb
<body>
  <%= render "layouts/navbar_top" %>
  <div class="contanier">
    <div class="row">
      <div class="col-sm-12">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <% 1.upto(@players.size - 1) do |n| %>
              <li data-target="#myCarousel" data-slide-to="#{n}"></li>
              <% end %>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="item active">
								<% f = @players.first %>
								<%= link_to(find_pic(f), player_path(f)) %>
								<div class="carousel-caption">
									<h3><%= f.name %></h3>
									<h4>#<%= f.number %></h4>
								</div>
              </div>
							<% @players.drop(1).each do |p| %>
							<div class="item">
								<%= link_to(find_pic(p), player_path(p)) %>
								<div class="carousel-caption">
									<h3><%= p.name %></h3>
									<h4>#<%= p.number %></h4>
								</div>
							</div>
							<% end %>            
	          </div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="icon-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="icon-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>

</body>

<%= render "layouts/footer" %>

app/views/players/show.html.erb
<body>
    <%= render "layouts/navbar_top" %>
	<div class="container">
        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                <%= find_pic(@player) %>
            </div>

            <div class="col-md-4">
                <h3>자기소개</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <h3>Things I Like</h3>
                <ul>
                    <li>Lorem Ipsum</li>
                    <li>Dolor Sit Amet</li>
                    <li>Consectetur</li>
                    <li>Adipiscing Elit</li>
                </ul>
                <h3><%= link_to("Post as #{@player.name}", new_player_blog_path(@player)) %></h3>
            </div>

        </div>

	</div>

</body>

<%= render "layouts/footer" %>

app/views/shared/_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <header>
      <h2>
        <% if current_user %>
          <%= "Come on #{@current_user.name}," %><br>
          fix the errors.
        <% else %>
          Please correct the following <%= pluralize(@user.errors.count, "error") %>:
        <% end %>
      </h2>
    </header>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- use bootstrap -->

app/views/users/_form.html.erb
<%= form_for @user, :class => "form-signin" do |f| %>
  <%= render "shared/errors" %>
<div class="form-group">
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name, autofocus: true, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :username, "Username:" %>
  <%= f.text_field :username, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email, "Email:" %>
  <%= f.email_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :number, "Number:" %>
  <%= f.number_field :number, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password, "Password:" %>
  <%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, "Confirm Password:" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :intro, "Tell us about yourself:" %>
  <%= f.text_area :intro, class: "form-control", rows: 5 %>
</div>
<p>
  <% if current_user %>
    <%= f.submit "Update", class: "btn btn-default btn-primary btn-block" %>
    <%= link_to("Delete Account", @user, method: :delete, class: "btn btn-default btn-primary btn-block", data: { confirm: 'Are you sure?' }) %>
  <% else %>
    <%= f.submit "Sign up", class: "btn btn-default btn-primary btn-block" %>
  <% end %>
  <%= link_to("Cancel", players_path, class: "btn btn-default btn-primary btn-block") %>
</p>
<% end %>

app/views/users/edit.html.erb
<body>
	<div class="container form-padding">
		<div class="border-form-div">
			<h2>Editing <%= @user.name %></h2>

			<%= render "form" %>

		</div>
	</div>
</body>
<%= render "layouts/footer" %>

app/views/users/home.html.erb
<body>
    <%= flash_messages %>
    <div class="container" id="top">
        <%= image_tag("main_narrow.png", class: "header") %>
    </div>

    <div class="container">
        <hr>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 text-center">
                <%= link_to news_path do %>
                    <span class="glyphicon glyphicon-envelope" 
                    style="font-size: 3em; color: #000000"></span>
                <% end %>
                <h3>RnC News</h3>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 text-center">
                <%= link_to players_path do %>
                    <span class="glyphicon glyphicon-sunglasses" 
                    style="font-size: 3em; color: #000000"></span>
                <% end %>
                <h3>RnC Players</h3>
            </div>
        </div>
        <hr>
    </div>

</body>

<%= render '/layouts/footer' %>

app/views/users/index.html.erb
<body>
  <div class="contanier">
    <div class="row">
      <div class="col-sm-12">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <% 1.upto(@users.size - 1) do |n| %>
              <li data-target="#myCarousel" data-slide-to="#{n}"></li>
              <% end %>
            </ol>
            <% if any_user? %>
              <div class="carousel-inner" role="listbox">
                <div class="item active">
  								<% f = @users.first %>
  								<%= link_to(image_tag(gravatar_id(f)), user_path(f)) %>
  								<div class="carousel-caption">
  									<h3><%= f.name %></h3>
  									<h4>#<%= f.number %></h4>
  								</div>
                </div>
  							<% @users.drop(1).each do |p| %>
  							<div class="item">
  								<%= link_to(image_tag(gravatar_id(p)), user_path(p)) %>
  								<div class="carousel-caption">
  									<h3><%= p.name %></h3>
  									<h4>#<%= p.number %></h4>
  								</div>
  							</div>
							<% end %>            
	          </div>
            <% end %>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="icon-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="icon-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>

</body>

<%= render "layouts/footer" %>

app/views/users/new.html.erb
<body>
	<div class="container form-padding">
		<div class="border-form-div">
			<h2>Welcome to RnC!</h2>

			<%= render "form" %>

		</div>
	</div>
</body>
<%= render "layouts/footer" %>

app/views/users/show.html.erb
<body>
	<div class="container">
        <div class="row">

        
            <div class="col-lg-6 col-md-6 col-sm-6 user-show">
                <%= image_tag gravatar_id(@user) %>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6">

                <h3><%= "#{@user.name} ##{@user.number}"%></h3>

                <p><%= @user.intro %></p>

            </div>

            <div class="col-xs-12">
                <% if @user.blogs.any? %>
                    <p><h4><%= link_to("See all posts by #{@user.name}", 
                                user_blogs_path(@user)) %></h4></p>
                <% end %>
            </div>
        </div>

	</div>

</body>

<%= render "layouts/footer" %>